name: Auto-DDNS

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "* */1 * * *"

env:
  api_key: ${{ secrets.api_key }}

jobs:
  auto-ddns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto DDNS
        run: |
          bash start.sh
